name: action test
run-name: 更新IPTV并推送
on: [push]
env:
  TZ: Asia/Shanghai
jobs:
  job1:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r ./requirements.txt
      - name: Running
        run: python3 ./main.py
      - name: Commit
        env:
          GIT_NAME: GitHub Actions[Bot]
          GIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          git config --local user.name $GIT_NAME
          git config --local user.email $GIT_EMAIL
          git add ./iptv.txt
          git commit -m "Github action update at `date '+%Y-%m-%d %H:$M:%S'`."
      - name: push
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git remote add target git@github.com:ailx1101/aptv.git
          git push target HEAD:refs/heads/master
          

